version: "3.0"

services:
  workspace:
    build: .
    tty: true
    volumes:
      - ~/.aws/:/root/.aws:ro
      - .:/app
    ports:
      - "9000:9000"
    environment:
      - 'PS1=[\u@\h \W] \$$ '
    command: /bin/bash -c "bash"
